# Generated by Django 4.2.25 on 2025-11-09 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('bio', models.TextField(blank=True, verbose_name='Биография')),
            ],
            options={
                'verbose_name': 'Артист',
                'verbose_name_plural': 'Артисты',
            },
        ),
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('release_type', models.CharField(choices=[('album', 'Альбом'), ('ep', 'EP'), ('single', 'Сингл')], default='album', max_length=10, verbose_name='Тип')),
                ('cover', models.ImageField(blank=True, null=True, upload_to='covers/', verbose_name='Обложка')),
                ('release_date', models.DateField(verbose_name='Дата релиза')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='releases', to='catalog.artist')),
            ],
            options={
                'verbose_name': 'Релиз',
                'verbose_name_plural': 'Релизы',
                'ordering': ['-release_date'],
            },
        ),
        migrations.CreateModel(
            name='Track',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название')),
                ('audio_file', models.FileField(upload_to='tracks/', verbose_name='Аудиофаил')),
                ('track_number', models.PositiveSmallIntegerField(default=1, verbose_name='Номер трека')),
                ('release', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tracks', to='catalog.release')),
            ],
            options={
                'verbose_name': 'Трек',
                'verbose_name_plural': 'Треки',
                'ordering': ['track_number'],
            },
        ),
    ]
